2015-07-01 23:24:12,422 |-0.0.0.0-8443-exec-1 |EntitySaxReader               |E| An error occurred saving the data, rolling back transaction (true)
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1417) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.writeValues(EntitySaxReader.java:329) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:299) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:235) [ofbiz-entity-test.jar:?]
	at org.ofbiz.webtools.WebToolsServices.parseEntityXmlFile(WebToolsServices.java:459) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webtools.WebToolsServices.entityImport(WebToolsServices.java:200) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:341) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:696) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:421) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:211) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:90) [ofbiz-webapp.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api-3.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api-3.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:317) [ofbiz-webapp.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)))
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:883) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:189) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.ofbiz.entity.GenericDataSourceException: SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:424) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.apache.derby.impl.jdbc.EmbedSQLException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.apache.derby.iapi.error.StandardException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.ForeignKeyRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.GenericRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.RISetChecker.doFKCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
2015-07-01 23:24:12,948 |-0.0.0.0-8443-exec-1 |ServiceDispatcher             |E| Error in Service [parseEntityXmlFile]: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:24:13,185 |-0.0.0.0-8443-exec-1 |ServiceDispatcher             |E| Error in Service [entityImport]: ERROR: parsing file: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:24:13,209 |-0.0.0.0-8443-exec-1 |RequestHandler                |E| Request entityImport caused an error with the following message: ERROR: parsing file: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:24:12.284(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:24:12.236(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:36:33,481 |-0.0.0.0-8443-exec-1 |GenericDelegator              |E| Failure in create operation for entity [Fund]: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)). Rolling back transaction.
2015-07-01 23:36:33,527 |-0.0.0.0-8443-exec-1 |GenericDelegator              |E| Failure in storeAll operation: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))). Rolling back transaction.
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)))
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:883) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.writeValues(EntitySaxReader.java:329) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:299) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:235) [ofbiz-entity-test.jar:?]
	at org.ofbiz.webtools.WebToolsServices.parseEntityXmlFile(WebToolsServices.java:459) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webtools.WebToolsServices.entityImport(WebToolsServices.java:200) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:341) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:696) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:421) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:211) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:90) [ofbiz-webapp.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api-3.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api-3.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:317) [ofbiz-webapp.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:189) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
Caused by: org.ofbiz.entity.GenericDataSourceException: SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:424) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
Caused by: org.apache.derby.impl.jdbc.EmbedSQLException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
Caused by: org.apache.derby.iapi.error.StandardException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.ForeignKeyRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.GenericRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.RISetChecker.doFKCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
2015-07-01 23:36:33,537 |-0.0.0.0-8443-exec-1 |EntitySaxReader               |E| An error occurred saving the data, rolling back transaction (true)
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1417) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.writeValues(EntitySaxReader.java:329) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:299) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:235) [ofbiz-entity-test.jar:?]
	at org.ofbiz.webtools.WebToolsServices.parseEntityXmlFile(WebToolsServices.java:459) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webtools.WebToolsServices.entityImport(WebToolsServices.java:200) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:341) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:696) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:421) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:211) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:90) [ofbiz-webapp.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api-3.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api-3.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:317) [ofbiz-webapp.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)))
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:883) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:189) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.ofbiz.entity.GenericDataSourceException: SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:424) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.apache.derby.impl.jdbc.EmbedSQLException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.apache.derby.iapi.error.StandardException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.ForeignKeyRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.GenericRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.RISetChecker.doFKCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
2015-07-01 23:36:34,086 |-0.0.0.0-8443-exec-1 |ServiceDispatcher             |E| Error in Service [parseEntityXmlFile]: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:36:34,265 |-0.0.0.0-8443-exec-1 |ServiceDispatcher             |E| Error in Service [entityImport]: ERROR: parsing file: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:36:34,277 |-0.0.0.0-8443-exec-1 |RequestHandler                |E| Request entityImport caused an error with the following message: ERROR: parsing file: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][fundName,Savings Fund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:36:33.345(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:36:33.294(java.sql.Timestamp)][statusId,FNDSTAT_ACT(java.lang.String)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:37:50,940 |-0.0.0.0-8443-exec-7 |GenericDelegator              |E| Failure in create operation for entity [Fund]: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)). Rolling back transaction.
2015-07-01 23:37:50,945 |-0.0.0.0-8443-exec-7 |GenericDelegator              |E| Failure in storeAll operation: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))). Rolling back transaction.
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)))
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:883) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.writeValues(EntitySaxReader.java:329) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:299) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:235) [ofbiz-entity-test.jar:?]
	at org.ofbiz.webtools.WebToolsServices.parseEntityXmlFile(WebToolsServices.java:459) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webtools.WebToolsServices.entityImport(WebToolsServices.java:200) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:341) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:696) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:421) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:211) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:90) [ofbiz-webapp.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api-3.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api-3.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:317) [ofbiz-webapp.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:189) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
Caused by: org.ofbiz.entity.GenericDataSourceException: SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:424) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
Caused by: org.apache.derby.impl.jdbc.EmbedSQLException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
Caused by: org.apache.derby.iapi.error.StandardException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.ForeignKeyRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.GenericRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.RISetChecker.doFKCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	... 51 more
2015-07-01 23:37:50,963 |-0.0.0.0-8443-exec-7 |EntitySaxReader               |E| An error occurred saving the data, rolling back transaction (true)
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1417) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.writeValues(EntitySaxReader.java:329) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:299) [ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.util.EntitySaxReader.parse(EntitySaxReader.java:235) [ofbiz-entity-test.jar:?]
	at org.ofbiz.webtools.WebToolsServices.parseEntityXmlFile(WebToolsServices.java:459) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webtools.WebToolsServices.entityImport(WebToolsServices.java:200) [ofbiz-webtools.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
	at org.ofbiz.service.engine.StandardJavaEngine.serviceInvoker(StandardJavaEngine.java:100) [ofbiz-service.jar:?]
	at org.ofbiz.service.engine.StandardJavaEngine.runSync(StandardJavaEngine.java:57) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:400) [ofbiz-service.jar:?]
	at org.ofbiz.service.ServiceDispatcher.runSync(ServiceDispatcher.java:232) [ofbiz-service.jar:?]
	at org.ofbiz.service.GenericDispatcherFactory$GenericDispatcher.runSync(GenericDispatcherFactory.java:83) [ofbiz-service.jar:?]
	at org.ofbiz.webapp.event.ServiceEventHandler.invoke(ServiceEventHandler.java:341) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.runEvent(RequestHandler.java:696) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:421) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:211) [ofbiz-webapp.jar:?]
	at org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:90) [ofbiz-webapp.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api-3.0.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api-3.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:317) [ofbiz-webapp.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [tomcat-7.0.59-catalina.jar:7.0.59]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-7.0.59-tomcat-coyote.jar:7.0.59]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)))
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:883) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:189) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.ofbiz.entity.GenericDataSourceException: SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:424) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.apache.derby.impl.jdbc.EmbedSQLException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
Caused by: org.apache.derby.iapi.error.StandardException: INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.ForeignKeyRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.GenericRIChecker.doCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.RISetChecker.doFKCheck(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source) ~[derby-10.8.2.2.jar:?]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.ofbiz.entity.jdbc.SQLProcessor.executeUpdate(SQLProcessor.java:420) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.singleInsert(GenericDAO.java:184) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:126) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.datasource.GenericHelperDAO.create(GenericHelperDAO.java:70) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.create(GenericDelegator.java:859) ~[ofbiz-entity-test.jar:?]
	at org.ofbiz.entity.GenericDelegator.storeAll(GenericDelegator.java:1382) ~[ofbiz-entity-test.jar:?]
	... 50 more
2015-07-01 23:37:50,968 |-0.0.0.0-8443-exec-7 |ServiceDispatcher             |E| Error in Service [parseEntityXmlFile]: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:37:50,969 |-0.0.0.0-8443-exec-7 |ServiceDispatcher             |E| Error in Service [entityImport]: ERROR: parsing file: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:37:50,983 |-0.0.0.0-8443-exec-7 |RequestHandler                |E| Request entityImport caused an error with the following message: ERROR: parsing file: ERROR parsing Entity Xml file: org.xml.sax.SAXException: A transaction error occurred reading data
org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))) (org.ofbiz.entity.GenericEntityException: Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.)) (Error while inserting: [GenericEntity:Fund][createdStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][createdTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)][fundId,SavingsFund(java.lang.String)][lastUpdatedStamp,2015-07-01 23:37:50.931(java.sql.Timestamp)][lastUpdatedTxStamp,2015-07-01 23:37:50.923(java.sql.Timestamp)] (SQL Exception while executing the following:INSERT INTO OFBIZ.FUND (FUND_ID, FUND_NAME, STATUS_ID, STATUS_DATE, LONG_DESCRIPTION, OPENING_DATE, CLOSURE_DATE, FIN_ACCOUNT_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (INSERT on table 'FUND' caused a violation of foreign key constraint 'FUND_FND_DETS' for key (SavingsFund).  The statement has been rolled back.))))
2015-07-01 23:41:01,572 |0.0.0.0-8443-exec-12 |DatabaseUtil                  |E| ModelEntity was null and is required to delete a table
2015-07-01 23:44:02,472 |OFBiz-config-1       |DatabaseUtil                  |E| WARNING: Column [FUND_ID] of table [OFBIZ.FUND_DETAILS] of entity [FundDetails] IS a primary key in the database, but IS NOT a primary key in the entity definition. The primary key for this table needs to be re-created or modified so that this column is NOT part of the primary key.
2015-07-01 23:45:15,078 |-0.0.0.0-8443-exec-4 |DatabaseUtil                  |E| WARNING: Column [FUND_ID] of table [OFBIZ.FUND_DETAILS] of entity [FundDetails] IS a primary key in the database, but IS NOT a primary key in the entity definition. The primary key for this table needs to be re-created or modified so that this column is NOT part of the primary key.
2015-07-01 23:48:28,041 |-0.0.0.0-8443-exec-6 |DatabaseUtil                  |E| ModelEntity was null and is required to delete a table
2015-07-01 23:48:50,916 |0.0.0.0-8443-exec-12 |DatabaseUtil                  |E| Could not create table [OFBIZ.FUND_DETAILS]: SQL Exception while executing the following:
CREATE TABLE OFBIZ.FUND_DETAILS (FUND_ID VARCHAR(20), LAST_UPDATED_STAMP TIMESTAMP, LAST_UPDATED_TX_STAMP TIMESTAMP, CREATED_STAMP TIMESTAMP, CREATED_TX_STAMP TIMESTAMP,  PRIMARY KEY ())
Error was: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ")" at line 1, column 185.
2015-07-01 23:50:00,841 |OFBiz-config-1       |DatabaseUtil                  |E| WARNING: Column [FUND_ID] of table [OFBIZ.FUND_FIN_ACCOUNTS] of entity [FundFinAccounts] IS a primary key in the database, but IS NOT a primary key in the entity definition. The primary key for this table needs to be re-created or modified so that this column is NOT part of the primary key.
2015-07-01 23:50:42,609 |-0.0.0.0-8443-exec-1 |DatabaseUtil                  |E| WARNING: Column [FUND_ID] of table [OFBIZ.FUND_FIN_ACCOUNTS] of entity [FundFinAccounts] IS a primary key in the database, but IS NOT a primary key in the entity definition. The primary key for this table needs to be re-created or modified so that this column is NOT part of the primary key.
